import {RegUserMoleson} from './reg-data.model';
import {AccessLevel} from './access-level';
import {BaseModel} from '../../_base/crud/models/_base.model';
import {ReferralService} from '../../referral';
import {ReferralUserModel} from '../../referral/_models/referral-user.model';

export class User extends BaseModel {
  INN: string;
  accessLevel: AccessLevel;
  SNILS: string;
  amountOfPurchases: number;
  referralLink: string;
  money: number;
  birthday: string;
  citizenship: string;
  dateCreate: number;
  dateIssued: string;
  departmentCode: string;
  email: string;
  password: string;
  expectsWithdrawal: number;
  fullName: string;
  regDate: RegUserMoleson;
  gender: string;
  isInstallmentPlan: boolean;
  isVerified: boolean;
  isVerifiedMail: boolean;
  issued: string;
  level: number;
  passportId: string;
  passportImg: string;
  registrationAddress: string;
  shoppingInStructure: number;
  urlMailConfirmation: string;
  username: string;
  pic: string;
  avatar: string;
  passport: string;
  _id: string;
  accessToken: string;
  balance: number;
  picture: any;
  passport_page_1: any;
  passport_page_2: any;
  passport_page_3: any;
  phone: number;
  referral: ReferralUserModel;
  clear(): void {
    this.accessLevel = new AccessLevel();
    this.regDate = new RegUserMoleson();
    this.INN = '';
    this.SNILS = '';
    this.referralLink = '';
    this.amountOfPurchases = 0;
    this.money = 0;
    this.pic = './assets/media/users/default.jpg';
    this.birthday = '';
    this.citizenship = '';
    this.dateCreate = 0;
    this.dateIssued = '';
    this.departmentCode = '';
    this.email = '';
    this.expectsWithdrawal = 0;
    this.fullName = '';
    this.gender = '';
    this.isInstallmentPlan = false;
    this.isVerified = false;
    this.isVerifiedMail = false;
    this.passportId = '';
    this.passport = '';
    this.avatar = '';
    this.password = '';
    this.level = 0;
    this.phone = 0;
    this.accessToken = '';
    this.issued = '';
    this.passportImg = '';
    this.registrationAddress = '';
    this.shoppingInStructure = 0;
    this.urlMailConfirmation = '';
    this.username = '';
    this._id = '';
    this.referral = new ReferralUserModel(null);
  }
}
